name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step2 : Install dependencies
      - name: Install dependencies
        run: npm install
      #Step 3 : Build project
      - name: Build project
        run: npm run build

      # Step4 : Deploy to GitHub Pages
      - name: Deploy to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Ensure this matches your build output directory
         
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Main Directory
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Deploy to main directory"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}